# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Omni Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Omni Sample
  pod 'AlamofireImage'
  pod 'Alamofire'
  pod 'BTNavigationDropdownMenu', :git => 'https://github.com/PhamBaTho/BTNavigationDropdownMenu.git', :branch => 'swift-3.0'
  pod 'SideMenu'

end
